#!/usr/bin/env bash
set -e

# Set myhostname depending on the hostname the Postfix Pod runs on.
# The ID gets extracted from the hostname.
SERVER_ID="${HOSTNAME//worker/}"
sed "s/@ID@/${SERVER_ID}/g" /etc/postfix/main_multi.cf.tmpl > /etc/postfix/main.cf

# Create virtual mailbox database
postmap lmdb:/etc/postfix/vmailbox

# The optional virtual(5) alias table rewrites recipient
# addresses for all local, all virtual, and all remote  mail
# destinations. This is unlike the aliases(5) table which
# is used only for local(8) delivery.
postmap lmdb:/etc/postfix/virtual

# Rebuild the mail aliases database, /etc/aliases, after a change.
newaliases

# Run Postfix master process. Do not redirect stdin, stdout
# or stderr to /dev/null, and do not discard the controlling
# terminal (-d).
exec /usr/libexec/postfix/master -c /etc/postfix -d 2>&1

# Keep tail process running to pipe Postfix log to stdout.
tail -F /var/log/mail.log
